pip install attrs -U
pip install audioread -U
pip install backcall -U
pip install bleach -U
pip install cffi -U
pip install cycler -U
pip install decorator -U
pip install defusedxml -U
pip install entrypoints -U
pip install ipykernel -U
pip install ipython -U
pip install ipython-genutils -U
pip install ipywidgets -U
pip install jedi -U
pip install Jinja2 -U
pip install joblib -U
pip install jsonschema -U
pip install jupyter -U
pip install jupyter-client -U
pip install jupyter-console -U
pip install jupyter-core -U
pip install kiwisolver -U
pip install librosa -U
pip install llvmlite -U
pip install MarkupSafe -U
pip install matplotlib -U
pip install mistune -U
pip install nbconvert -U
pip install nbformat -U
pip install notebook -U
pip install numba -U
pip install numpy -U
pip install pandas -U
pip install pandocfilters -U
pip install parso -U
pip install pexpect -U
pip install pickleshare -U
pip install prometheus-client -U
pip install prompt-toolkit -U
pip install ptyprocess -U
pip install pycparser -U
pip install Pygments -U
pip install pyparsing -U
pip install pyrsistent -U
pip install python-dateutil -U
pip install pytz -U
pip install pyzmq -U
pip install qtconsole -U
pip install resampy -U
pip install scikit-learn -U
pip install scipy -U
pip install seaborn -U
pip install Send2Trash -U
pip install six -U
pip install SoundFile -U
pip install terminado -U
pip install testpath -U
pip install tornado -U
pip install traitlets -U
pip install wcwidth -U
pip install webencodings -U
pip install widgetsnbextension -U
